### ISSUE TITLE
RA is not properly detecting the joypad

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/retroarch-joypad-autoconfig#139]
RA has a problem to properly detect the right joypad, take a look:

```
RetroArch [INFO] :: [udev]: Plugged pad: DragonRise Inc.   Generic   USB  Joystick   (0079:0006) on port #0.
RetroArch [INFO] :: Autodetect: 100 profiles found
RetroArch [INFO] :: Autodetect: selected configuration: /home/sergio/.config/retroarch/autoconf/udev/DragonRise_Inc._PC_TWIN_SHOCK_Gamepad.cfg
RetroArch [INFO] :: [udev]: Pad #0 (/dev/input/event14) supports force feedback.
RetroArch [INFO] :: [udev]: Pad #0 (/dev/input/event14) supports 16 force feedback effects.
RetroArch [INFO] :: Found joypad driver: "udev".
```

I have the "DragonRise Inc.   Generic   USB  Joystick", but it's using the DragonRise_Inc._PC_TWIN_SHOCK_Gamepad.cfg file. They have the same product ID, but RA should not be capable to handle this in the right way, using the joypad names?

It's funny that if I use the autoconfig files at the root, it does work right:

```
RetroArch [INFO] :: [udev]: Plugged pad: DragonRise Inc.   Generic   USB  Joystick   (0079:0006) on port #0.
RetroArch [INFO] :: Autodetect: 100 profiles found
RetroArch [INFO] :: Autodetect: selected configuration: /usr/share/libretro/autoconfig/DragonRise_Inc.___Generic___USB__Joystick__.cfg
RetroArch [INFO] :: [udev]: Pad #0 (/dev/input/event14) supports force feedback.
RetroArch [INFO] :: [udev]: Pad #0 (/dev/input/event14) supports 16 force feedback effects.
RetroArch [INFO] :: Found joypad driver: "udev".
```

**Comment by fr500** [comment]
Many manufacturers do this, they use the same vid/pid all over.
Not much can be done about it unless one of the fields is different.

The autoconf system uses a scoring system with the following rules:
- VID + PID yields a score of 3
- Exact name match yields a score of 2
- A partial name match yields a score of 1

So in this case nothing ca be done, all the fields match, you should bug the manufacturer because there is no way to tell one from the other programatically

**Comment by Kivutar** [comment]
Yes. What said @fr500 about that problem is true. There is nothing we can do to support all of those joypads.

I would however correct what he said about the autoconf system, the score system combine all those methods by addition, so a joypad with a vid+pid+name match will give better result that a joypad with vid+pid.

Anyway, the consequences are the same, we can just close every issue and PR about these with a **won't fix** tag.

**Comment by fr500** [comment]
Yeah I forgot to mention it adds the values :+1:

**Comment by sergiobenrocha2** [comment]
But why is it working with the config files at the root?

**Comment by fr500** [comment]
Because it just makes a list of all the files in a folder, I'm not sure what the function uses as an ordering parameter but I guess for some reason it picks one in the first case and the other in the second case.

It uses the last found best matching config IIRC
