### ISSUE TITLE
Joypad not loading the config file properly

### ISSUE THREAD

**Issue by atilacamurca** [libretro/retroarch-joypad-autoconfig#189]
Hi,

I have a joypad with the configuration bellow:

```
Bus 002 Device 003: ID 0079:0006 DragonRise Inc. PC TWIN SHOCK Gamepad
```

There is a _DragonRise Inc. PC TWIN SHOCK Gamepad_ config file but when I turn lakka on it loads the file for _Retrolink_N64_USB_controller_.

Neither of them have the vendor_id above (**79**), so I created a _Retrolink_N64_USB_controller.cfg_ with the contents of _DragonRise_Inc._PC_TWIN_SHOCK_Gamepad.cfg_.

Do you guys have a better way, maybe adding a new cfg file with the vendor_id 79 and product_id 6?

**Comment by fr500** [comment]
RetroArch uses a scoring system.
Your pad in fact matches with that Retrolink since

0x0079 = 121 decimal
0x0006 = 6 decimal

It uses the last found match with the highest score.
VID + PID accounts to 3 points
perfect name match accounts to 2 points
partial name match accounts to 1 point

My guess is that the name doesn't match, your pad shows up as:
DragonRise Inc. PC TWIN SHOCK Gamepad

And the autocfg has:
DragonRise Inc.   Generic   USB  Joystick  

So try changing the file to match with the name.
You can also make a profile for your pad and it would work perfectly by doing the following:

- Load RetroArch
- Set your autoconf dir to some directory were you can read/write, I am not a lakka user so I'm not sure if you can modify those @Kivutar should know
- Navigate to Input Settings 
- Go to user 1 binds
- Select User 1 default all
- Select User 1 bind all, bind anything that you don't have to a single button
- Try to correct anything that might be mapped wrong, the GUI is a bit to sensitive, also clean up any binds for buttons you don't have
- Select User 1 Save Autoconfig
Then make sure to select User 1 default all so the manual bindings are cleared, restart and test, if everything went smoothly it should now detect your controller just fine

**Comment by fr500** [comment]
This really isn't our fault but shitty manufacturers using the same VID/PID for different controllers.

**Comment by atilacamurca** [comment]
Damn those manufacturers! :rage: 

Thanks for the clarification.

Just one more thing the file <https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/DragonRise_Inc._PC_TWIN_SHOCK_Gamepad.cfg> has the following line:

`input_device = "DragonRise Inc.   Generic   USB  Joystick  "`

So if you say the perfect name affects the score in 2 points than it should be renamed, right?

It seems that this file was duplicated (from <https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/DragonRise_Inc.___Generic___USB__Joystick__.cfg>) and the `input_device` value was not updated.

**Comment by fr500** [comment]
could be, not sure

**Comment by sergiobenrocha2** [comment]
@atilacamurca, I have this joypad

```
Bus 003 Device 002: ID 0079:0006 DragonRise Inc. PC TWIN SHOCK Gamepad
```

    It seems that this file was duplicated (from https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/DragonRise_Inc.___Generic___USB__Joystick__.cfg) and the input_device value was not updated.

Actually, RetroArch is recognizing it as "DragonRise Inc.   Generic   USB  Joystick  " for some reason, and it's ignoring the string from lsusb
