### ISSUE TITLE
Standarization

### ISSUE THREAD

**Issue by fr500** [libretro/retroarch-joypad-autoconfig#267]
I'm planning to rewrite the save and load autoconf functions to be smarter so I'd like people who have contributed to chime in into this.

I want to use the following standard:

VID#####_PID#####_NAME.cfg

Name would always be sanitized (no spaces, no symbols, only numbers and letters).
Right now some controllers have really stupid names (leading and trailing spaces, slashes, trademark and registered symbols) and each time one of these is commited something breaks (the android build system doesn't like such characters when building the APK)

It could also speed up loading somewhat, it could look directly for VID#####_PID#####_NAME.cfg

**Comment by fr500** [comment]
@paalfe @magwe

**Comment by paalfe** [comment]
That could be useful, yes.

**Comment by magwe** [comment]
Sound good to me. When I have created new files I have been trying to follow whatever established naming pattern there is, but it is a mess, so this sounds much better.

But I would like to take the opportunity to again highlight a related issue. NAME needs to be whatever name the contributor thinks is reasonable. The are many instances of controllers where VID:PID and reported name are the same for different controllers with different layouts. For example the 0x0079:0x0006-chip is mostly used for DualShock style controllers, but it is also used by a N64 style controller which obviously uses a completely different mapping. Contrary to what the .cfg file says for the N64 controller they all report "Dragonrise generic USB controler" or something like that.

There is no way of separating these without manual interaction. (for example: ask the user to press the "B" button and check witch config fits.)

And also related to this (sorry for highjacking) most of the controllers I have seen try to follow the DualShock button mapping as long as it makes sense. So SNES controllers (which are a subset of dualshock) tend to map X=0,A=1,B=2,Y=3,L=4,R=5, Null(l2)=6, Null(r2)=7, Select=8, Start=9, Null(l3)=10, Null(r3)=11.  I think the DualShock mapping should be the default for any unconfigured controller. (Without looking I am convinced that more than 50% of the configs would work perfectly with this default)

**Comment by paalfe** [comment]
This linux bash command gets vid:pid from cfg (requires cfget installed) and renames cfg files (+ replaces symbols not wanted with underscore) to "VID####_PID####_FILENAME_WITHOUT_SYMBOLS.cfg"
`for f in *.cfg; do vid="$(cfget -C "$f" input_vendor_id)"; pid="$(cfget -C "$f" input_product_id)"; mv "$f" "VID${vid//\"}_PID${pid//\"}_${f//[<>:\\|*\'\"?;=%,+ ()-]/_}"; done`

**Comment by fr500** [comment]
@magwe not sure about what you mean with dualshock, default and alternate layouts.
There is only one layout, RetroPad layout, and it's just like the WiiU Pro controller, not dualshock or anything.

Anyway, haven't decided anything, I had actually forgot about this.
Also I added a flag, input_swap_override = "true" if you want a NES pad for instance to retain A for OK, B for cancel when the global menu_swap_ok_cancel is enabled.

**Comment by magwe** [comment]
@fr500 sorry if I expressed myself unclearly. Dualshock config and default/alt. layout are not directly related.

Re: default/alt. Sometimes there are two config files that match a given VID:PID. Usually one of these is more common. That should be the default. The less common config should be selectable as an alternative layout.

Re: Dualshock. Most gamepads are clones of the duashock controller (WiiU Pro included) in terms of physical layout but that is not the point. There are many third party USB controllers that work with the ps3 and pc. That has establish somewhat of a standard when it comes to what button has what button id. Using RetroPad button names that button numbering is x=0, a=1, b=2, y=3, l=4, r=5, l2=6, r2=7, select=8, start=9, l3=10, r3=11 which I propose as a default setting for unrecognised gamepads. As I mentioned above, I have seen this button numbering used even for SNES-style controllers that leave 6 and 7 (L2/R2) unassigned and use 8 and 9 for select/start to match the dual shock standard. That being said, I think the genuine Sony Dual Shock controller assigns button numbers differently under linux for some reason, but I don't have one so I can't verify that.

Since Sony has trademarked the Triangle/Circle/Cross/Square symbols, unlicensed controllers usually use either similar symbols but with broken lines to not infringe on the trademark, or they use 1,2,3,4.

**Comment by Kivutar** [comment]
If we use this standard VID#####_PID#####_NAME.cfg it will be difficult to browse the files and find the one we're looking for.

**Comment by AnicetusCer** [comment]
agree with magwe and kivutar, I love the logic of your suggestion, but I just submitted a cfg for a crystal (see through) version (just released) of the wired Sony Dual Shock V2 controller "Model: CUH-ZCT2E" it has the same VID and PID but a slightly Different button layout then the Black DS4v2 controller.
Also as kivutar points out, as a human it would be difficult to find a specific config file by name, which helped me when creating crystal cfg.
Do agree though naming convention would be nice, Maybe;  "Company_ProductName_Version_Variation" Example "Sony_DS4_V2_0" "Sony_DS4_V2_Crystal"

**Comment by RobLoach** [comment]
A good example of a config file that's well documented is...
https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/3H%20Dual%20Arcade.cfg

Feel free to update configs where you see fit. Keeping the nice display name for the filename is desired.
