### ISSUE TITLE
Dual Shock 3 inputs not functioning in Linux

### ISSUE THREAD

**Issue by pepedopolous** [libretro/retroarch-joypad-autoconfig#437]
Using Arch Linux, if I upgrade the kernel to anything newer than 4.9.78-lts my Dual Shock 3 PS3 controller doesn't work. I cannot navigate the XMB and even the keyboard stops working except for the Ctrl+Alt+Backspace or Esc shortcuts.

So is this simply a kernel problem? I'm not sure. The controller gives apparently normal responses in the KDE System Settings joystick page, joytest-gtk, and functions normally under the Steam Big Picture Mode and Half Life 2 demo.

**Comment by samcv** [comment]
Hey @pepedopolous. I recently started using retroarch and when my DualShock3 was connected either by Bluetooth or USB it caused the keyboard input to work improperly. To fix this you just need to fix the mapping for the controller. Also make sure you don't do this with retroarch running or it will overwrite the config file.

1. Run retroarch with verbose settings: `retroarch -v 2>&1 | grep -Ei 'udev|autoconf'`. Mine says `[INFO] [udev]: Plugged pad: Sony PLAYSTATION(R)3 Controller (32903:2012) on port #0.` If yours has `32903:2012` as well then everything is ok and proceed. Otherwise you will need to edit the controller config's vendor alter `input_vendor_id = "32903"` and `input_product_id = "2012"` lines

2. Download this configuration I have made [Sony-PlayStation3-DualShock3-Controller-CECHZC2U.cfg.txt](https://github.com/libretro/retroarch-joypad-autoconfig/files/1784892/Sony-PlayStation3-DualShock3-Controller-CECHZC2U.cfg.txt)

2. Put this file in `~/.config/retroarch/autoconfig/udev`

3. We will need to remove the controller settings in `~/.config/retroarch/retroarch.cfg` because even with the new map file, the settings will still be set in `retroarch.cfg`. The following assumes you have the controller setup as player 1, otherwise change the grep to refer to the proper player number. This will remove the mappings but **only** for buttons, not for keyboard settings.
```
cd ~/.config/retroarch
grep -Ev 'input_player1_.*_btn' ../retroarch.cfg > ../retroarch.cfg.new
mv retroarch.cfg retroarch.cfg.bak
mv retroarch.cfg.new retroarch.cfg
```

4. When retroarch starts up again, it will locate the controller settings and apply them.

  * If the controller has been bound to player 1 also stores controller inputs.

Attached I have a proper controller mapping, 
I have no clue about kernel version (that could be related) but I am on 4.15 and I have never used Retroarch with anything earlier than 4.14. I also

**Comment by pepedopolous** [comment]
Thanks for your help.

1) It says on the back CECHZC2E(followed by a smaller capital A).
2) I ran the command and found that the ids were different (1356:616). 
3) So I edited the files autoconfig files in the udev folder. First, one called Sony-Playstation3-DualShock3-Controller-Bluetooth.cfg. This made no difference and when I launched retroarch again it was using a different config file (USB instead of Bluetooth, the same id numbers 1356:616). So I then edited the USB autoconfig file. Then when I launched retroarch for a third time, it said it was using the PANHAI config file (which doesn't seem to have any id numbers). However, now the controller was working  very well in tandem with the keyboard (just the central PS button wasn't working). After I downloaded the file and followed the steps with the retroarch,cfg file, I launched retroarch again but it was now using the SHANWAN configuration file and the PS button still isn't working.

Note: I could have messed up but where in your command it reads '../retroarch.cfg > ../retroarch.cfg.new' this didn't work for me. I used it without the dots and forward slashes.

**Comment by pepedopolous** [comment]
Thanks for your help.

1) The model of the controller is E not U at the end.
2) The id numbers are different- 1356:616
3) The steps fixed the issues so the controller and keyboard seem to work just as before :-)

**Comment by samcv** [comment]
@pepedopolous you should reopen this issue. It is still not closed, even though I was able to fix your issue. This issue should stay open until mine and your id numbers are added to the config so they work out of the box.

**Comment by orbea** [comment]
I think this will probably fix it if you have an official sony dual shock 3.

https://github.com/libretro/retroarch-joypad-autoconfig/pull/494

**Comment by RobLoach** [comment]
I'm not sure what's needed in here. Mind uploading your config or updates as a Pull Request?

**Comment by samcv** [comment]
@RobLoach this issue might be fixed now. I know I don't have issues anymore, and I think I'm a fresh installation as well (this ticket is almost 3 years old). So I think having it closed now is fine.
