### ISSUE TITLE
8bitdo sn30 pro firmware 1.29 mapping changes

### ISSUE THREAD

**Issue by ghost** [libretro/retroarch-joypad-autoconfig#499]
From firmware 1.29 onwards 8bitdo sn 30 pro requires to be paired with

Start + x in usb mode, uses the pid and mapping of the xbox 360 wired controller

In bluetooth mode required to use start + y in pro controller mode

Previous discussed with hunterk https://forums.libretro.com/t/8bitdo-sn-30-pro-firmware-1-29-changes/20162/6

**Comment by hizzlekizzle** [comment]
Thanks for the PR. It's a pretty major change, so let me get some more input from folks with 8bitdo pads to test.

**Comment by omegaoncoffee** [comment]
> Thanks for the PR. It's a pretty major change, so let me get some more input from folks with 8bitdo pads to test.

Hi, first thanks for dealing with it. It's painfull I imagine. 

Did some more testing with a fresh install and found out mapping in bluetooth start + y uses the config of the switch pro controller. Nothing to remap here. It's this map [https://github.com/libretro/retroarch-joypad-autoconfig/blob/0ebca0c491992dbbcdb5f960e261236c547b0ba3/udev/Pro%20Controller.cfg](url)

New goal for fw 1.29 is to encourage people to use start + x and start + y on bluetooth and remove the 1.26 config files. I don't have the sf 30 pro to test, but I think it's the same solution when comparing pid/vid.

**Comment by 5schatten** [comment]
Well I don't see what new behaviour was introduced with firmware v1.29. I've got 2 SF 30 Pro controllers and both work this way since the beginning. Start + X (XInput) & Start + Y are somewhat compat profiles for Switch and other Systems that already support those controllers while Start + B starts the controller with a 8bitdo vendor profile in DInput mode.
So it's completely normal to act as a different type of controller depending on what startup you choose.

**Comment by RobLoach** [comment]
Tehre's been some updates across 8bitdo configs. Going to close this for now. Feel free to re-open if you're having issues.... Also, the 8bitdo website has some firmware updates too!!!!
