### ISSUE TITLE
Add support for Microsoft SideWinder Joystick

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [libretro/retroarch-joypad-autoconfig#55]
This device is not supported:  
![Microsoft SideWinder Joystick](http://media.engadget.com/img/product/27/l5x/sidewinder-joystick-2e9p.jpg)

It has an analogue joystick, a trigger button, a thumb button, 2 more buttons on top of the joystick, and a cluster of 4 buttons on the left. (The slider probably has little to no use for RetroArch.)

It shows up with the device name of `Microsoft SideWinder Joystick`:  
![screenshot - 06242015 - 12 33 34 pm](https://cloud.githubusercontent.com/assets/2776014/8336892/3fc855a2-1a6d-11e5-8237-7e4922d849d1.png)

**Comment by hizzlekizzle** [comment]
I don't think any of the devs/contributors have one of these, so someone would have to make an autoconfig file for it and submit a PR.

**Comment by lasers** [comment]
Close this?

We have few SideWinder cfgs and while that might not be same, it's impossible to stay consistent with this kind of joystick. When asked for button B, A, X, Y, etc... one would not know which button would be the most appropriate to press. Everything is spreading all over the place. Some buttons on joystick will behind the joystick, in front of the joystick, at the base of the joystick, etc.

I didn't upload my `CH Gamestick 3D USB Joystick` for this reason. I think it's best for user to keep the config that they themselves configure with their own joystick because that cfg may not be agreeable across multiple systems and between owners.

Also, it had been a while.

**Comment by JamesTheAwesomeDude** [comment]
@hizzlekizzle I have one, and could provide any/all data needed.

But, though, I think @lasers brings up a good point.
