### ISSUE TITLE
Idea to handle conflicting VID / PID gamepads

### ISSUE THREAD

**Issue by ReenigneArcher** [libretro/retroarch-joypad-autoconfig#641]
I have two possible ideas to handle conflicting game pads.

One idea would be to see if the VID / PID is a duplicate, and if so show a message asking the user which gamepad it is. Also with the option to not ask again for this VID / PID.

Another idea would be to have a priority list within RetroArch. The users could move gamepads up or down.

Perhaps it could be a combination of both, and of course give the users an option to reset the priorities to default.

**Comment by abdulahmad** [comment]
Priority list still leaves someone in the dust unfortunately. But I do think showing a message should be the way to go

This is what I think should be done:

- Add REVID as a tiebreaker if VID/PID/Device are all the same
- If multiple autoconfigs for the same controller are detected, Pop-up a vertical list showing the Device Display Name (or Device Name if no Display name given), and tell the user to select the correct controller and press ANY button. I think it should be ANY button, because that guarantees the user can go forward even if the mapping is not what they expect.
- There also needs to be an easy way in the Settings->Controls->Input X Binds menu to re-open the autoconfig selection and select another autoconfig.

**Comment by offalynne** [comment]
contributing to the spitballing -- xb360ce's database and html5gamepad dot com's logs may be useful to mine for comparative market share of conflicting devices if a deliberate priority is going to be introduced

**Comment by RobLoach** [comment]
This sounds like an issue for the RetroArch issue queue rather than here. Thanks! Feel free to make any changes you find directly in here as Pull Requests.
